---
- name: "Mario installation"
  become: yes
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create default containers
      docker_container:
        name: "super-mario"
        image: "pengbai/docker-supermario"
        state: started
        restart: "yes"
        ports: "8080:8080"
